apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  # Peamine container
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

  # Sidecar container - logide lugemine
  - name: log-reader
    image: busybox
    command: ["sh", "-c", "tail -f /logs/access.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /logs

  # Shared volume
  volumes:
  - name: shared-logs
    emptyDir: {}
