apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    app: user-service
    version: "1.0"
spec:
  containers:
  - name: user-service
    image: user-service:1.0
    imagePullPolicy: Never  # Kasuta local image'i (Minikube)
    ports:
    - containerPort: 3000
      name: http
    env:
    - name: PORT
      value: "3000"
    - name: NODE_ENV
      value: "production"
    - name: DB_HOST
      value: "postgres"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "user_service_db"
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "postgres"
    - name: JWT_SECRET
      value: "temporary-secret-key"
