apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP  # Default (internal access only)
  selector:
    app: user-service
  ports:
  - name: http
    port: 80        # Service port
    targetPort: 3000  # Container port
    protocol: TCP
