apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "supersecret123"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: "my-super-secret-key-123456"
  JWT_EXPIRES_IN: "24h"
