# ==========================================================================
# CD Workflow - User Service
# ==========================================================================
# Continuous Deployment pipeline:
# - Determine environment from branch
# - Deploy with Helm (environment-specific values)
# - Health checks
# - Automatic rollback on failure
# - Notifications
# ==========================================================================

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main
      - develop
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/user-service
  HELM_CHART_PATH: ./helm-chart

jobs:
  # ==========================================================================
  # Job 1: Determine Environment
  # ==========================================================================
  determine-environment:
    name: Determine Environment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      namespace: ${{ steps.set-env.outputs.namespace }}
      values-file: ${{ steps.set-env.outputs.values-file }}
      image-tag: ${{ steps.set-env.outputs.image-tag }}

    steps:
      - name: Determine environment from branch
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV="${{ inputs.environment }}"
          else
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            case $BRANCH in
              main)
                ENV="production"
                ;;
              staging)
                ENV="staging"
                ;;
              develop)
                ENV="development"
                ;;
              *)
                echo "Unknown branch: $BRANCH"
                exit 1
                ;;
            esac
          fi

          echo "environment=$ENV" >> $GITHUB_OUTPUT
          echo "namespace=$ENV" >> $GITHUB_OUTPUT
          echo "values-file=values-$ENV.yaml" >> $GITHUB_OUTPUT

          # Image tag: branch-sha for traceability
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ github.ref_name }}-${{ github.sha }}"
          else
            TAG="${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.head_sha }}"
          fi
          echo "image-tag=$TAG" >> $GITHUB_OUTPUT

          echo "## Deployment Configuration" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** $ENV" >> $GITHUB_STEP_SUMMARY
          echo "- **Namespace:** $ENV" >> $GITHUB_STEP_SUMMARY
          echo "- **Values File:** values-$ENV.yaml" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag:** $TAG" >> $GITHUB_STEP_SUMMARY

  # ==========================================================================
  # Job 2: Deploy to Environment
  # ==========================================================================
  deploy:
    name: Deploy to ${{ needs.determine-environment.outputs.environment }}
    runs-on: ubuntu-latest
    needs: determine-environment

    environment:
      name: ${{ needs.determine-environment.outputs.environment }}
      url: https://${{ needs.determine-environment.outputs.environment == 'production' && '' || needs.determine-environment.outputs.environment + '.' }}kirjakast.cloud/api/users

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.29.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Create namespace if not exists
        run: |
          kubectl create namespace ${{ needs.determine-environment.outputs.namespace }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Helm upgrade (atomic deployment)
        id: helm-deploy
        run: |
          helm upgrade --install user-service ${{ env.HELM_CHART_PATH }} \
            --namespace ${{ needs.determine-environment.outputs.namespace }} \
            --values ${{ env.HELM_CHART_PATH }}/${{ needs.determine-environment.outputs.values-file }} \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set image.tag=${{ needs.determine-environment.outputs.image-tag }} \
            --wait \
            --timeout 5m \
            --atomic \
            --cleanup-on-fail

      - name: Get deployment status
        run: |
          echo "## Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          kubectl get deployment user-service \
            -n ${{ needs.determine-environment.outputs.namespace }} \
            -o wide >> $GITHUB_STEP_SUMMARY || echo "Deployment not found" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pods:" >> $GITHUB_STEP_SUMMARY
          kubectl get pods \
            -n ${{ needs.determine-environment.outputs.namespace }} \
            -l app=user-service >> $GITHUB_STEP_SUMMARY || echo "No pods found" >> $GITHUB_STEP_SUMMARY

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/user-service \
            -n ${{ needs.determine-environment.outputs.namespace }} \
            --timeout=5m

      - name: Health check
        id: health-check
        run: |
          # Get service endpoint
          if [[ "${{ needs.determine-environment.outputs.environment }}" == "production" ]]; then
            ENDPOINT="https://kirjakast.cloud/api/users/health"
          else
            ENDPOINT="https://${{ needs.determine-environment.outputs.environment }}.kirjakast.cloud/api/users/health"
          fi

          echo "Testing endpoint: $ENDPOINT"

          # Wait for endpoint to be ready (max 2 min)
          for i in {1..24}; do
            if curl -f -s -o /dev/null "$ENDPOINT"; then
              echo "✅ Health check passed!"
              echo "## Health Check" >> $GITHUB_STEP_SUMMARY
              echo "✅ Endpoint is healthy: $ENDPOINT" >> $GITHUB_STEP_SUMMARY
              exit 0
            fi
            echo "Attempt $i/24: Endpoint not ready yet..."
            sleep 5
          done

          echo "❌ Health check failed after 2 minutes"
          echo "## Health Check" >> $GITHUB_STEP_SUMMARY
          echo "❌ Endpoint failed health check: $ENDPOINT" >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Smoke tests
        run: |
          # Get service endpoint
          if [[ "${{ needs.determine-environment.outputs.environment }}" == "production" ]]; then
            BASE_URL="https://kirjakast.cloud/api/users"
          else
            BASE_URL="https://${{ needs.determine-environment.outputs.environment }}.kirjakast.cloud/api/users"
          fi

          echo "## Smoke Tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Test 1: Health endpoint
          if curl -f "$BASE_URL/health"; then
            echo "✅ Health endpoint: OK" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Health endpoint: FAILED" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          # Test 2: Ready endpoint
          if curl -f "$BASE_URL/ready"; then
            echo "✅ Ready endpoint: OK" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Ready endpoint: FAILED" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All smoke tests passed!" >> $GITHUB_STEP_SUMMARY

      - name: Rollback on failure
        if: failure() && steps.helm-deploy.outcome == 'success'
        run: |
          echo "⚠️ Deployment failed health checks, rolling back..."
          helm rollback user-service 0 \
            -n ${{ needs.determine-environment.outputs.namespace }} \
            --wait \
            --timeout 3m

          echo "## Automatic Rollback" >> $GITHUB_STEP_SUMMARY
          echo "⚠️ Deployment rolled back due to failed health checks" >> $GITHUB_STEP_SUMMARY

      - name: Notify Slack (success)
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [[ -n "$SLACK_WEBHOOK" ]]; then
            curl -X POST "$SLACK_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d "{
                \"text\": \"✅ Deployment successful!\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Deployment Successful* ✅\n*Environment:* ${{ needs.determine-environment.outputs.environment }}\n*Image:* ${{ env.DOCKER_IMAGE }}:${{ needs.determine-environment.outputs.image-tag }}\n*Deployed by:* ${{ github.actor }}\"
                    }
                  }
                ]
              }"
          fi

      - name: Notify Slack (failure)
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [[ -n "$SLACK_WEBHOOK" ]]; then
            curl -X POST "$SLACK_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d "{
                \"text\": \"❌ Deployment failed!\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*Deployment Failed* ❌\n*Environment:* ${{ needs.determine-environment.outputs.environment }}\n*Image:* ${{ env.DOCKER_IMAGE }}:${{ needs.determine-environment.outputs.image-tag }}\n*Workflow:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>\"
                    }
                  }
                ]
              }"
          fi

  # ==========================================================================
  # Job 3: Deployment Summary
  # ==========================================================================
  summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [determine-environment, deploy]
    if: always()

    steps:
      - name: Generate summary
        run: |
          echo "## CD Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | ${{ needs.determine-environment.outputs.environment }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Namespace | ${{ needs.determine-environment.outputs.namespace }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Image Tag | ${{ needs.determine-environment.outputs.image-tag }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Deploy Status | ${{ needs.deploy.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.deploy.result }}" == "success" ]]; then
            echo "### ✅ Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Deployment Failed!" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
